### ISSUE TITLE
Clean/responsive layout and css

### ISSUE THREAD

**Issue by gorj-tessella** [nebiolabs/plate-map#15]
The current implementation makes extensive use of elements with fixed heights and widths, float tags, and other css positioning behaviors that are not adequately responsive to the size of the user interface. This should be cleaned up. 

In particular the following specific items must be addressed: 

- If more than 5 or 6 fields are on a tab, scroll bars are automatically triggered. The vertical scrollbar may be unavoidable, but the horizontal scrollbar is also triggered because there is insufficient space for vertical scrollbar when triggered. There are two possible solutions: 
  - Make the field widths adapt to their container, and shrink when the scrollbar is triggered
  - Less preferentially, leave enough room for scrollbar to activate. The problem is scrollbar width varies. 
- Allow main interface to expand to fit page, mainly for benefit of bottom table? 
- Unit dropdown should be to right of input field, not on top of it. 
- Use table to align fields?

**Comment by gorj-tessella** [comment]
@bwlang what is the oldest browser we have to support with plate-map?

**Comment by bwlang** [comment]
If it’s good on  modern Firefox and chrome that’s plenty.



brad
On Sep 20, 2017, at 9:48 AM, Jeremy Gore <notifications@github.com<mailto:notifications@github.com>> wrote:


@bwlang<https://github.com/bwlang> what is the oldest browser we have to support with plate-map?

**Comment by gorj-tessella** [comment]
Modern browsers have big improvements to css, so that will make layout much easier.

**Comment by gorj-tessella** [comment]
Changes incorporated into current master
