### ISSUE TITLE
Reconciling gem-plate-map and master. 

### ISSUE THREAD

**Issue by gorj-tessella** [nebiolabs/plate-map#16]
The gem-plate-map branch is being actively developed, however all changes are applicable to master. The problem is that the two branches have different hierarchies. 

We need to decide if both branches should be maintained, or only the gem version. Alternatively, we could have a separate project for the gem version, but then things will need to be updated twice.

**Comment by bwlang** [comment]
i think we should just keep the gem version - easier to deploy.

**Comment by gorj-tessella** [comment]
OK, I will make features/ekappotis/plate-map-gem the new master. I will retain the old master.

**Comment by gorj-tessella** [comment]
Merged master, deleted features/ekappotis/gem-plate-map

**Comment by gorj-tessella** [comment]
The state of the old master is now on branch plain-js
