### ISSUE TITLE
Could someone make a tutorial video how this can be used?

### ISSUE THREAD

**Issue by lubwen** [nebiolabs/plate-map#24]
Could someone make a tutorial video how this can be used?

This tool looks pretty nice. However, I do not how to get started with it.

Thanks a lot.

**Comment by bwlang** [comment]
@lubwen thanks for your interest... we are still working on the implementation, but we'll document a bit more about how to use this soon.

**Comment by lubwen** [comment]
I would like to volunteer to make a demo website. I think this will worth the effort because it will help people on how to use the plate-map app. What do you guys think?

**Comment by bwlang** [comment]
Sure - thanks for taking on the project. 
Let us know if you run into questions!

**Comment by sktrinh12** [comment]
hi, is the documentation for this finished? wanted to look into an example app, but can't find any. thanks.
