### ISSUE TITLE
How hard would it be to make this work for 384-well plate maps?

### ISSUE THREAD

**Issue by lubwen** [nebiolabs/plate-map#33]
I am wondering how hard it is to make this work for 384-well plate maps. I adopted the code for a 96-well plate maps project and it worked very well. We might need to work with 384-well plate maps in the future so I am wondering about this...

Thanks to everyone for this wonderful code repo!

**Comment by bwlang** [comment]
Hi : 
We've made a lot of progress lately so I hope you're using the latest stuff... I don't know how well the coloring and labeling will fit with a 384 well layout... but the underlying system should be fine with 384. We normally compose 384 well plates from pre-defined 96 well plates elsewhere in the UI.
