### ISSUE TITLE
Pull in any relevant code from ebase repo's platemap branch

### ISSUE THREAD

**Issue by bwlang** [nebiolabs/plate-map#4]

**Comment by mikelynchtessella** [comment]
I've had a look at the Eric's commits, and there are only two that aren't in [tessella-dev](/nebiolabs/ebase/tree/tessella-dev) already. These are [fd6631d] and [3d51b9f], and the same changes appear to have been made in plate-map already.

**Comment by bwlang** [comment]
sounds good thanks!

**Comment by mikelynchtessella** [comment]
Sorry Brad – comparing the code was mislead me (due to the renaming of selects and multiselects over time). Speaking with Jeremy, a small change is necessary that he'll do. At the moment, only the logic for multiselects is in the plate-map repository.
