### ISSUE TITLE
Any plan on releasing to npm ?

### ISSUE THREAD

**Issue by ArnaudPel** [nebiolabs/plate-map#42]
In the readme you mention this project
> is designed to be easily utilized in the context of a larger scientific software application

Composing third-party code libraries in large (in fact, any) application usually comes with some sort of dependency (package) manager.

Any plans on [releasing to npm](https://docs.npmjs.com/getting-started/creating-node-modules) maybe ?

**Comment by bwlang** [comment]
This is a good suggestion ... i'm not sure when we'll get to look at it  but I agree that this is mostly js so we should release it in that environment.  I'm thinking about using bower as well which might help to elminate the embedded dependencies.

**Comment by ArnaudPel** [comment]
Glad we agree. Bower themselves recommend [migrating away from them](https://bower.io/blog/2017/how-to-migrate-away-from-bower/). They suggest Yarn as an alternative, but two arguments would make me lean towards npm. Disclaimer: I am partial to npm since that's what we are currently using :)

- Feedback form someone [who went to yarn then back to npm](https://mixmax.com/blog/to-yarn-and-back-again-npm/)
- Yarn [can [...] install any package from the npm registry](https://yarnpkg.com/lang/en/docs/migrating-from-npm/) anyway

Moreover, I believe the choice between the two is not so definitive, by that I mean that once the lib is packaged correctly, moving from one package manager to the other shouldn't be too hard.

**Comment by ArnaudPel** [comment]
On a more practical note. We've decided to try and integrate `plate-map` to our own front-end app. If that goes well and suits our needs, I'd be keen for my team to have a go at packaging it, and submit a PR if all goes well.
