### ISSUE TITLE
Required fields don't work well

### ISSUE THREAD

**Issue by bwlang** [nebiolabs/plate-map#66]
warning about requiring 100% completion does not clear the save button - can't try again.
it's not clear which fields are required

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/61636/87865500-2beaf900-c944-11ea-9794-ac484adc8b2a.png">

**Comment by bwlang** [comment]
more details from andrew:

1. In order to save a new wellset (at least using the visual editor), certain fields need to be filled out, or PolBase will give a "100% completion percentage is required for save back. Please go back and revise missing fields" error message; it will then give the spinning wheel icon indicating that it's attempting to save, but will not be able to do so, so any unsaved progress on the wellset up to that point will be unrecoverable. This can be avoided, thoguh, by being sure to fill out the Well > Excluded, Rxn > Reaction temp and Rxn > Freeze thaw count fields before trying to save. A wellset with those three fields filled out is considered "100% complete", at least in the visual editor.

2. To select multiple wells in the visual plate editor, users should now press "shift" instead of "ctrl".

**Comment by bwlang** [comment]
@gorj-tessella  is this still relevant?

**Comment by gorj-tessella** [comment]
1 was fixed back in July, and should be present on the current ebase. As for 2, we have always used shift to select multiple wells, so I'm not sure why he is saying ctrl.
