### ISSUE TITLE
no longer available on npm?

### ISSUE THREAD

**Issue by alice-insitro** [nebiolabs/plate-map#67]
When trying to install by running `npm install plate-map --save` with node version` 12.18.3` and npm version `6.14.7`, I get the following:

```
http fetch GET 200 https://registry.npmjs.org/plate-map 14ms (from cache)
silly fetchPackageMetaData error for plate-map@latest No valid versions available for plate-map
```

same after cleaning the cache:
`http fetch GET 200 https://registry.npmjs.org/plate-map 170ms`

**Comment by bwlang** [comment]
I think this may be referring to 
https://www.npmjs.com/package/plate-map-app
apparently a CZB project.
